### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by notnot** [fabiokung/shm#1]
Hi, i am seeing a memory leak in a very simple scenario:

```
memo, err := shm.Open(memName, os.O_RDWR|os.O_CREATE, 0666)
if err != nil {
	return -1.0, fmt.Errorf("shm.Open(): %s", err)
}
defer memo.Close()
defer shm.Unlink(memo.Name())
```

When you do this repeatedly, the memory usage of the process grows and grows.

I'm on Ubuntu linux.

**Comment by notnot** [comment]
ignore this, it was a bug elsewhere in my code

**Comment by kolinfluence** [comment]
possible to show an example how u manage to read and write the shm.Open mem area? just a simple example will do? thx
